import { blue, green, orange, red, slate, yellow } from "@radix-ui/colors";
import { createStitches } from "@stitches/react";
import { OctoProperty } from "./octoUI.config";

export const createOcto = createStitches;

export const theme = {
  prefix: "octo-UI",
  theme: {
    colors: {
      primary1: blue.blue1,
      primary2: blue.blue2,
      primary3: blue.blue3,
      primary4: blue.blue4,
      primary5: blue.blue5,
      primary6: blue.blue6,
      primary7: blue.blue7,
      primary8: blue.blue8,
      primary9: blue.blue9,
      primary10: blue.blue10,
      primary11: blue.blue11,
      primary12: blue.blue12,

      secondary1: orange.orange1,
      secondary2: orange.orange2,
      secondary3: orange.orange3,
      secondary4: orange.orange4,
      secondary5: orange.orange5,
      secondary6: orange.orange6,
      secondary7: orange.orange7,
      secondary8: orange.orange8,
      secondary9: orange.orange9,
      secondary10: orange.orange10,
      secondary11: orange.orange11,
      secondary12: orange.orange12,

      accent1: yellow.yellow1,
      accent2: yellow.yellow2,
      accent3: yellow.yellow3,
      accent4: yellow.yellow4,
      accent5: yellow.yellow5,
      accent6: yellow.yellow6,
      accent7: yellow.yellow7,
      accent8: yellow.yellow8,
      accent9: yellow.yellow9,
      accent10: yellow.yellow10,
      accent11: yellow.yellow11,
      accent12: yellow.yellow12,

      grey1: slate.slate1,
      grey2: slate.slate2,
      grey3: slate.slate3,
      grey4: slate.slate4,
      grey5: slate.slate5,
      grey6: slate.slate6,
      grey7: slate.slate7,
      grey8: slate.slate8,
      grey9: slate.slate9,
      grey10: slate.slate10,
      grey11: slate.slate11,
      grey12: slate.slate12,

      error1: red.red1,
      error2: red.red2,
      error3: red.red3,
      error4: red.red4,
      error5: red.red5,
      error6: red.red6,
      error7: red.red7,
      error8: red.red8,
      error9: red.red9,
      error10: red.red10,
      error11: red.red11,
      error12: red.red12,

      success1: green.green1,
      success2: green.green2,
      success3: green.green3,
      success4: green.green4,
      success5: green.green5,
      success6: green.green6,
      success7: green.green7,
      success8: green.green8,
      success9: green.green9,
      success10: green.green10,
      success11: green.green11,
      success12: green.green12,
    },
    sizes: {
      1: 1,
      2: 2,
      3: 4,
      4: 6,
      5: 8,
      6: 10,
      7: 12,
      8: 14,
      9: 16,
      10: 20,
      11: 24,
      12: 32,
      13: 40,
      14: 48,
      15: 56,
      16: 64,
      17: 72,
    },
    space: {
      1: 1,
      2: 2,
      3: 4,
      4: 6,
      5: 8,
      6: 10,
      7: 12,
      8: 14,
      9: 16,
      10: 20,
      11: 24,
      12: 32,
      13: 40,
      14: 48,
      15: 56,
      16: 64,
      17: 72,
    },
    fonts: {
      untitled: "Untitled Sans, -apple-system, system-ui, sans-serif",
      mono: "Söhne Mono, menlo, monospace",
    },
    fontSizes: {
      1: "12px",
      2: "14px",
      3: "16px",
      4: "18px",
      5: "20px",
      6: "22px",
      7: "28px",
      8: "36px",
      9: "60px",
    },
    radii: {
      1: "2px",
      2: "4px",
      3: "8px",
      4: "16px",
      round: "50%",
      pill: "9999px",
    },
    zIndices: {
      1: "100",
      2: "200",
      3: "300",
      4: "400",
      max: "999",
    },
    borderStyles: {},
    borderWidths: {},
    fontWeights: {},
    letterSpacings: {},
    lineHeights: {},
    shadows: {},
    transitions: {},
  },
  utils: {
    p: (value: OctoProperty<"padding">) => ({
      padding: value,
    }),
    pt: (value: OctoProperty<"paddingTop">) => ({
      paddingTop: value,
    }),
    pr: (value: OctoProperty<"paddingRight">) => ({
      paddingRight: value,
    }),
    pb: (value: OctoProperty<"paddingBottom">) => ({
      paddingBottom: value,
    }),
    pl: (value: OctoProperty<"paddingLeft">) => ({
      paddingLeft: value,
    }),
    px: (value: OctoProperty<"padding">) => ({
      paddingLeft: value,
      paddingRight: value,
    }),
    py: (value: OctoProperty<"padding">) => ({
      paddingTop: value,
      paddingBottom: value,
    }),
    m: (value: OctoProperty<"margin">) => ({
      margin: value,
    }),
    mt: (value: OctoProperty<"marginTop">) => ({
      marginTop: value,
    }),
    mr: (value: OctoProperty<"marginRight">) => ({
      marginRight: value,
    }),
    mb: (value: OctoProperty<"marginBottom">) => ({
      marginBottom: value,
    }),
    ml: (value: OctoProperty<"marginLeft">) => ({
      marginLeft: value,
    }),
    mx: (value: OctoProperty<"margin">) => ({
      marginLeft: value,
      marginRight: value,
    }),
    my: (value: OctoProperty<"margin">) => ({
      marginTop: value,
      marginBottom: value,
    }),
    ta: (value: OctoProperty<"textAlign">) => ({ textAlign: value }),
    fd: (value: OctoProperty<"flexDirection">) => ({ flexDirection: value }),
    fw: (value: OctoProperty<"flexWrap">) => ({ flexWrap: value }),
    ai: (value: OctoProperty<"alignItems">) => ({ alignItems: value }),
    ac: (value: OctoProperty<"alignContent">) => ({ alignContent: value }),
    jc: (value: OctoProperty<"justifyContent">) => ({ justifyContent: value }),
    as: (value: OctoProperty<"alignSelf">) => ({ alignSelf: value }),
    fg: (value: OctoProperty<"flexGrow">) => ({ flexGrow: value }),
    fs: (value: OctoProperty<"flexShrink">) => ({ flexShrink: value }),
    fb: (value: OctoProperty<"flexBasis">) => ({ flexBasis: value }),
    bc: (value: OctoProperty<"backgroundColor">) => ({
      backgroundColor: value,
    }),
    br: (value: OctoProperty<"borderRadius">) => ({
      borderRadius: value,
    }),
    btrr: (value: OctoProperty<"borderTopRightRadius">) => ({
      borderTopRightRadius: value,
    }),
    bbrr: (value: OctoProperty<"borderBottomRightRadius">) => ({
      borderBottomRightRadius: value,
    }),
    bblr: (value: OctoProperty<"borderBottomLeftRadius">) => ({
      borderBottomLeftRadius: value,
    }),
    btlr: (value: OctoProperty<"borderTopLeftRadius">) => ({
      borderTopLeftRadius: value,
    }),
    bs: (value: OctoProperty<"boxShadow">) => ({ boxShadow: value }),
    lh: (value: OctoProperty<"lineHeight">) => ({ lineHeight: value }),
    ox: (value: OctoProperty<"overflowX">) => ({ overflowX: value }),
    oy: (value: OctoProperty<"overflowY">) => ({ overflowY: value }),
    pe: (value: OctoProperty<"pointerEvents">) => ({ pointerEvents: value }),
    us: (value: OctoProperty<"userSelect">) => ({
      WebkitUserSelect: value,
      userSelect: value,
    }),
    size: (value: OctoProperty<"width">) => ({
      width: value,
      height: value,
    }),
    appearance: (value: OctoProperty<"appearance">) => ({
      WebkitAppearance: value,
      appearance: value,
    }),
    userSelect: (value: OctoProperty<"userSelect">) => ({
      WebkitUserSelect: value,
      userSelect: value,
    }),
    backgroundClip: (value: OctoProperty<"backgroundClip">) => ({
      WebkitBackgroundClip: value,
      backgroundClip: value,
    }),
    fullscreen: (value: OctoProperty<"position">) => ({
      position: value,
      top: 0,
      bottom: 0,
      left: 0,
      right: 0,
    }),
  },
};

export const defaultOctoConfig = createOcto(theme);
